apiVersion: v2
name: observability-bundle
description: A Helm chart for Giant Swarm's collection of observability tools.
home: https://github.com/giantswarm/observability-bundle
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
kubeVersion: ">=1.19.0-0"
sources:
  - https://github.com/giantswarm/observability-bundle
version: 2.6.0
annotations:
  io.giantswarm.application.app-type: bundle
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: atlas
